name: Deploy to Aws
'on':
  push:
    branches:
      - production
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      -
        name: run maven
        run: |
          mvn  clean install  -DskipTests -B
          mkdir -p target/dependency && (cd target/dependency; unzip ../*.jar)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/se331-greenlake-backend:latest
      -
        name: prepare the docker-compose run
        run: |
          mkdir project-backend
          cp docker-compose-prod.yml project/docker-compose.yml
          cd project-backend
          docker-compose -H ${{ secrets.DOCKER_HOST }} down
          docker-compose -H ${{ secrets.DOCKER_HOST }} pull
          docker-compose -H ${{ secrets.DOCKER_HOST }} up -d
